import '../model/book.dart';

final List<Book> books = [
  Book('A sútil arte de ligar o foda-se', '', 'https://m.media-amazon.com/images/I/6175IU0qFgL._SY522_.jpg', 'https://amzn.to/3sD5yI1'),
  Book('As 48 leis do poder', '', 'https://m.media-amazon.com/images/I/617iS--XOQL._SY522_.jpg', 'https://amzn.to/3ucwXkH'),
  Book('Poder & Manipulacao', '', 'https://m.media-amazon.com/images/I/41GnAlGKIlL._SY445_SX342_.jpg', 'https://amzn.to/3vzPGXO'),
  Book('Como fazer amigos e influenciar pessoas', '', 'https://m.media-amazon.com/images/I/71x-i7sKSvL._SY522_.jpg', 'https://amzn.to/40w2073'),
  Book('Como fazer amigos e influenciar pessoas na era digital', '', 'https://m.media-amazon.com/images/I/41pwZLPjGfL._SY445_SX342_.jpg', 'https://amzn.to/3MDsPk4'),
  Book('Maquiavel: O príncipe', '', 'https://m.media-amazon.com/images/I/81h4CdNxdgL._SY522_.jpg', 'https://amzn.to/3FVlKaQ'),
  Book('Sun Tzu A arte da guerra', '', 'https://m.media-amazon.com/images/I/31QzwYLvuCL._SY445_SX342_.jpg', 'https://amzn.to/3SJ4m0i'),
  Book('Musashi: O livro dos cinco anéis', '', 'https://m.media-amazon.com/images/I/71LHnnl1QhL._SY522_.jpg', 'https://amzn.to/49xtZap'),
  Book('Atitude mental positiva', '', 'https://m.media-amazon.com/images/I/41GXO9WeYML._SY445_SX342_.jpg', 'https://amzn.to/469nE2b'),
  Book('Mais esperto que o Diabo', '', 'https://m.media-amazon.com/images/I/512TscpFEVL._SY445_SX342_.jpg', 'https://amzn.to/49u3CSS'),
  Book('O ego é seu inimigo', '', 'https://m.media-amazon.com/images/I/413fuqqQrZL._SY445_SX342_.jpg', 'https://amzn.to/3FWqFbA'),
  Book('O segredo', '', 'https://m.media-amazon.com/images/I/51xrozxLlPL._SX342_SY445_.jpg', 'https://amzn.to/479Kwje'),
  Book('Quem pensa enriquece', '', 'https://m.media-amazon.com/images/I/41ro37po+CL._SY445_SX342_.jpg', 'https://amzn.to/46990YE'),
  Book('O homem mais rico da Babilônia', '', 'https://m.media-amazon.com/images/I/51cB4wSNxQL._SY445_SX342_.jpg', 'https://amzn.to/46ampjj'),
  Book('Pai rico, pai pobre', '', 'https://m.media-amazon.com/images/I/51aLmULO+LL._SY445_SX342_.jpg', 'https://amzn.to/3su8reh'),
  Book('Os segredos da mente milionária', '', 'https://m.media-amazon.com/images/I/81fxmkE+tNL._SY522_.jpg', 'https://amzn.to/3SHAzW9'),
  Book('A psicologia financeira', '', 'https://m.media-amazon.com/images/I/41htlT5B29S._SY445_SX342_.jpg', 'https://amzn.to/3std886'),
  Book('Do mil ao milhão: Sem cortar o cafezinho', '', 'https://m.media-amazon.com/images/I/412y2rFbc7L._SY445_SX342_.jpg', 'https://amzn.to/40Gkj9F'),
  Book('O milionário mora ao lado', '', 'https://m.media-amazon.com/images/I/51yF+ij9ooL._SY445_SX342_.jpg', 'https://amzn.to/47uQAmc'),
  Book('Comece pelo mais difícil', '', 'https://m.media-amazon.com/images/I/61rvWTjvMeL._SY522_.jpg', 'https://amzn.to/3swZGAb'),
  Book('O monge e o executivo', '', 'https://m.media-amazon.com/images/I/41jyDCYMAlL._SY445_SX342_.jpg', 'https://amzn.to/3ucyRBT'),
  Book('Líderes se servem por último', '', 'https://m.media-amazon.com/images/I/41t0rW658CL._SY445_SX342_.jpg', 'https://amzn.to/40FVDyc'),
  Book('O clique de 1 bilhão de dólares', '', 'https://img.linkme.bio/img/','https://amzn.to/3QPS8lj'),
  Book('Uma verdade incomoda', '', 'https://m.media-amazon.com/images/I/91zHKJgfm6S._SY522_.jpg','https://amzn.to/3smOyWC'),
  Book('Isso nunca vai funcionar','','https://m.media-amazon.com/images/I/41C1QC1gY0L._SY445_SX342_.jpg','https://amzn.to/47uiwqe',),
  Book('As cinco linguagens do amor', '','https://m.media-amazon.com/images/I/412lekY6fJL._SY445_SX342_.jpg','https://amzn.to/47LKdvd'),
  Book('Um amor para recordar', '','https://m.media-amazon.com/images/I/41VEKu+TQ-L._SY445_SX342_.jpg','https://amzn.to/3SCgxfn'),
  Book('Querido Jonh', '', 'https://m.media-amazon.com/images/I/51eeKLD0JBL._SY445_SX342_.jpg','https://amzn.to/3SJ4i0y',),
  Book('Um homem de sorte','','https://m.media-amazon.com/images/I/51fxfKAGrHL._SY445_SX342_.jpg','https://amzn.to/3GesnVX',),
  Book('A revolução dos bichos', '','https://m.media-amazon.com/images/I/91BsZhxCRjL._SY522_.jpg','https://amzn.to/3SHjb3P', ),
  Book('O cálice dos Deuses: Série Percy Jackson e os olimpianos','', 'https://m.media-amazon.com/images/I/516mK15dmBL._SY445_SX342_.jpg','https://amzn.to/3QUPRWb'),
  Book('Jogos vorazes','' ,'https://m.media-amazon.com/images/I/41XpauMr8ML._SX342_SY445_.jpg','https://amzn.to/3MCP8pY'),
];